"""Removendo a tabela playlist

Revision ID: 286ea9d9eb12
Revises: 83724e1ed488
Create Date: 2026-02-01 22:02:45.728665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '286ea9d9eb12'
down_revision: Union[str, Sequence[str], None] = '83724e1ed488'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # DROP DEPENDENT TABLE FIRST
    op.drop_index(op.f('ix_playlist_items_id'), table_name='playlist_items')
    op.drop_table('playlist_items')
    
    # THEN DROP PARENT TABLE
    op.drop_index(op.f('ix_playlists_id'), table_name='playlists')
    op.drop_table('playlists')
    
    op.drop_index(op.f('idx_tracks_name_artists_trgm'), table_name='tracks', postgresql_ops={"((name::text || ' '::text) || artists::text)": 'gin_trgm_ops'}, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_tracks_name_artists_trgm'), 'tracks', [sa.literal_column("((name::text || ' '::text) || artists::text)")], unique=False, postgresql_ops={"((name::text || ' '::text) || artists::text)": 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_table('playlists',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('system_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('playlists_owner_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('playlists_pkey'))
    )
    op.create_index(op.f('ix_playlists_id'), 'playlists', ['id'], unique=False)
    op.create_table('playlist_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('playlist_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('track_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('system_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], name=op.f('playlist_items_playlist_id_fkey')),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], name=op.f('playlist_items_track_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('playlist_items_pkey'))
    )
    op.create_index(op.f('ix_playlist_items_id'), 'playlist_items', ['id'], unique=False)
    # ### end Alembic commands ###
