"""add columns in users table

Revision ID: b296ffaee605
Revises: 9b3459626100
Create Date: 2026-01-22 13:37:15.100312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b296ffaee605'
down_revision: Union[str, Sequence[str], None] = '9b3459626100'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('spotify_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('spotify_access_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('spotify_refresh_token', sa.String(), nullable=True))
    op.drop_column('users', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'spotify_refresh_token')
    op.drop_column('users', 'spotify_access_token')
    op.drop_column('users', 'spotify_id')
    # ### end Alembic commands ###
